<a href="https://colab.research.google.com/github/wani0502/Machine-Learning-Algorithms/blob/main/MultipleRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [2]:
X,y=make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [3]:
df=pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [4]:
df.shape

(100, 3)

In [5]:
df.head()

   feature1  feature2      target
0 -1.727831  0.137889   23.907382
1 -0.825209 -0.298952   -8.113424
2  0.182693 -0.118448  -50.950767
3 -0.271505 -0.129814    6.197172
4  0.190207  0.067763  104.980328

In [7]:
df.sample()

    feature1  feature2     target
30  0.743039  0.689976  29.537718

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lr=LinearRegression()

In [13]:
lr.fit(X_train,y_train)

LinearRegression()

In [14]:
y_pred=lr.predict(X_test)

In [16]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [17]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 39.41161189498916
MSE 2355.503326517602
R2 score 0.24630961722908729

In [19]:
lr.coef_

array([11.66553481, 32.40951894])

In [20]:
lr.intercept_

np.float64(-1.0505102534194892)